package daemon

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/Mathias-g/Servitor/internal/honker"
	"github.com/Mathias-g/Servitor/internal/protocol"
	"github.com/Mathias-g/Servitor/internal/secret"
	"github.com/Mathias-g/Servitor/internal/worker"
)

func daemonExtPath(t *testing.T) string {
	t.Helper()
	p := os.Getenv("HONKER_EXTENSION_PATH")
	if p == "" {
		t.Skip("HONKER_EXTENSION_PATH not set; skipping daemon runner integration test")
	}
	if _, err := os.Stat(p); err != nil {
		t.Skipf("HONKER_EXTENSION_PATH %s not readable: %v", p, err)
	}
	return p
}

// TestDaemonRunsQueuedJob boots the daemon with a store and a worker, enqueues
// a shell node through a second handle to the same file, and verifies the
// daemon's worker executes it and writes the result. This exercises the wiring
// in Run (worker loop + store ownership) end to end.
func TestDaemonRunsQueuedJob(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			Workers:      1,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()

	select {
	case <-started:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}

	// Second handle to the same file, used only to enqueue from the test.
	store, err := honker.Open(dbPath, ext)
	if err != nil {
		t.Fatalf("open test store: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })
	q := store.Queue("nodes", 30, 3)
	if _, err := q.Enqueue(worker.NodeJob{
		RunID: "r", WorkflowID: "wf", NodeID: "a", NodeName: "a",
		NodeType: "shell", Command: []string{"/bin/sh", "-c", `printf '{"ok":true}'`},
	}); err != nil {
		t.Fatalf("enqueue: %v", err)
	}

	deadline := time.After(5 * time.Second)
	for {
		res, err := store.ResultJSON("r", "a")
		if err != nil {
			t.Fatalf("result: %v", err)
		}
		if res != "" {
			break
		}
		select {
		case <-deadline:
			t.Fatal("daemon worker did not execute the queued node in time")
		case <-time.After(20 * time.Millisecond):
		}
	}

	cancel()
	select {
	case err := <-done:
		if err != nil {
			t.Fatalf("daemon shutdown error: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

// freePort allocates an ephemeral port, releases it, and returns the address.
// Reusing a just-released port is a minor race but reliable in practice for
// tests.
func freePort(t *testing.T) string {
	t.Helper()
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("free port: %v", err)
	}
	addr := l.Addr().String()
	_ = l.Close()
	return addr
}

const wfShellYAML = `
name: demo
triggers:
  - type: manual
nodes:
  - type: shell
    name: a
    command: "printf '{\"ok\":true}'"
`

// TestDaemonSubmitAndManual drives the control-plane registration and manual
// trigger through a running daemon: submit a workflow, trigger it, and verify
// the worker executes the run.
func TestDaemonSubmitAndManual(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			Workers:      1,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()

	select {
	case cpAddr := <-started:
		ctl := protocol.NewClient(cpAddr)
		if err := ctl.Health(ctx); err != nil {
			t.Fatalf("health: %v", err)
		}
		if _, err := ctl.Submit(ctx, []byte(wfShellYAML)); err != nil {
			t.Fatalf("submit: %v", err)
		}
		if err := ctl.Trigger(ctx, "demo", []byte(`{"x":1}`)); err != nil {
			t.Fatalf("trigger: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}

	// Verify the worker executed the run by reading results from a second
	// handle to the same file.
	store, err := honker.Open(dbPath, ext)
	if err != nil {
		t.Fatalf("open test store: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })

	deadline := time.After(5 * time.Second)
	for {
		// The run id is generated by the daemon as <name>-<unixnano>; we cannot
		// predict it, so poll for any node result row.
		n, _ := store.NodeResultCount()
		if n > 0 {
			break
		}
		select {
		case <-deadline:
			t.Fatal("worker did not execute the triggered run")
		case <-time.After(20 * time.Millisecond):
		}
	}

	cancel()
	select {
	case err := <-done:
		if err != nil {
			t.Fatalf("daemon shutdown error: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

const wfInternalUpstreamYAML = `
name: up
triggers:
  - type: manual
nodes:
  - type: shell
    name: a
    command: "printf '{\"ok\":true}'"
`

const wfInternalDownstreamYAML = `
name: down
triggers:
  - type: completed
    workflow: up
nodes:
  - type: shell
    name: b
    command: "printf '{\"fired\":true}'"
`

// TestDaemonInternalTrigger verifies that completing an upstream workflow fires
// an enabled workflow with an `internal` trigger naming it: submit both, run the
// upstream manually, and confirm the downstream runs too (two node results).
func TestDaemonInternalTrigger(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			Workers:      1,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()

	select {
	case cpAddr := <-started:
		ctl := protocol.NewClient(cpAddr)
		if err := ctl.Health(ctx); err != nil {
			t.Fatalf("health: %v", err)
		}
		if _, err := ctl.Submit(ctx, []byte(wfInternalUpstreamYAML)); err != nil {
			t.Fatalf("submit upstream: %v", err)
		}
		if _, err := ctl.Submit(ctx, []byte(wfInternalDownstreamYAML)); err != nil {
			t.Fatalf("submit downstream: %v", err)
		}
		if err := ctl.Trigger(ctx, "up", []byte(`{"x":1}`)); err != nil {
			t.Fatalf("trigger upstream: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}

	store, err := honker.Open(dbPath, ext)
	if err != nil {
		t.Fatalf("open test store: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })

	// The upstream run and the downstream run it fired each write a node result.
	deadline := time.After(5 * time.Second)
	for {
		n, _ := store.NodeResultCount()
		if n >= 2 {
			break
		}
		select {
		case <-deadline:
			t.Fatal("internal trigger did not run the downstream workflow")
		case <-time.After(20 * time.Millisecond):
		}
	}

	cancel()
	select {
	case err := <-done:
		if err != nil {
			t.Fatalf("daemon shutdown error: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

// TestDaemonWebhookReceiver verifies a signed Standard Webhooks request to the
// webhook listener enqueues a run.
func TestDaemonWebhookReceiver(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")
	whAddr := freePort(t)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			WebhookAddr:  whAddr,
			Workers:      1,
			Resolver:     secret.ResolverFromMap(map[string]string{"WH_SECRET": "s3cret"}),
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()

	select {
	case cpAddr := <-started:
		ctl := protocol.NewClient(cpAddr)
		if _, err := ctl.Submit(ctx, []byte(wfWebhookYAML)); err != nil {
			t.Fatalf("submit: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}

	// Send a signed webhook to the receiver.
	body := []byte(`{"event":"x"}`)
	ts := strconv.FormatInt(time.Now().Unix(), 10)
	id := "evt_1"
	mac := hmac.New(sha256.New, []byte("s3cret"))
	_, _ = mac.Write([]byte(id + "." + ts + "."))
	_, _ = mac.Write(body)
	sig := "v1," + base64.StdEncoding.EncodeToString(mac.Sum(nil))

	httpc := &http.Client{Timeout: 3 * time.Second}
	req, _ := http.NewRequestWithContext(ctx, http.MethodPost, "http://"+whAddr+"/hooks/demo", bytes.NewReader(body))
	req.Header.Set("webhook-id", id)
	req.Header.Set("webhook-timestamp", ts)
	req.Header.Set("webhook-signature", sig)
	resp, err := httpc.Do(req)
	if err != nil {
		t.Fatalf("webhook request: %v", err)
	}
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("webhook status = %d, want 200", resp.StatusCode)
	}

	store, err := honker.Open(dbPath, ext)
	if err != nil {
		t.Fatalf("open test store: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })

	// Event was persisted.
	deadline := time.After(5 * time.Second)
	for {
		n, _ := store.EventCount()
		if n > 0 {
			break
		}
		select {
		case <-deadline:
			t.Fatal("event was not persisted")
		case <-time.After(20 * time.Millisecond):
		}
	}

	// The worker ran the workflow.
	runDeadline := time.After(5 * time.Second)
	for {
		n, _ := store.NodeResultCount()
		if n > 0 {
			break
		}
		select {
		case <-runDeadline:
			t.Fatal("worker did not run the webhook-triggered workflow")
		case <-time.After(20 * time.Millisecond):
		}
	}

	cancel()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

const wfWebhookYAML = `
name: demo
triggers:
  - type: standard_webhook
    path: /hooks/demo
    secret: WH_SECRET
nodes:
  - type: shell
    name: a
    command: "printf '{\"ok\":true}'"
`

// TestDaemonRunsAndCancel verifies the runs/run/cancel control-plane surface:
// submit a manual workflow, trigger it, list runs, and cancel a run.
func TestDaemonRunsAndCancel(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			Workers:      1,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()

	var cpAddr string
	select {
	case cpAddr = <-started:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}
	ctl := protocol.NewClient(cpAddr)

	if _, err := ctl.Submit(ctx, []byte(wfManualYAML)); err != nil {
		t.Fatalf("submit: %v", err)
	}
	if err := ctl.Trigger(ctx, "demo", []byte(`{}`)); err != nil {
		t.Fatalf("trigger: %v", err)
	}

	// Find the run id from runs history.
	var runsBody string
	deadline := time.After(5 * time.Second)
	for {
		var err error
		runsBody, err = ctl.ListRuns(ctx)
		if err != nil {
			t.Fatalf("runs: %v", err)
		}
		if runsBody != "[]" && runsBody != "null" && runsBody != "" {
			break
		}
		select {
		case <-deadline:
			t.Fatal("no runs appeared")
		case <-time.After(20 * time.Millisecond):
		}
	}
	var runs []struct {
		ID     string `json:"ID"`
		Status string `json:"Status"`
	}
	if err := json.Unmarshal([]byte(runsBody), &runs); err != nil {
		t.Fatalf("decode runs %q: %v", runsBody, err)
	}
	if len(runs) == 0 {
		t.Fatal("expected at least one run")
	}
	runID := runs[0].ID

	// Inspect the run.
	body, err := ctl.GetRun(ctx, runID)
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if !strings.Contains(body, runID) {
		t.Fatalf("run body %q missing id %s", body, runID)
	}
	// The run's node outcomes are returned under a `nodes` key (not `steps`).
	if !strings.Contains(body, `"nodes"`) {
		t.Fatalf("run body %q missing nodes key", body)
	}

	// Cancel it (idempotent enough; if it already completed, cancel still works).
	if err := ctl.Cancel(ctx, runID); err != nil {
		t.Fatalf("cancel: %v", err)
	}

	cancel()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

const wfManualYAML = `
name: demo
triggers:
  - type: manual
nodes:
  - type: shell
    name: a
    command: "printf '{\"ok\":true}'"
`

// TestDaemonUpdate verifies update replaces a registered workflow and errors
// when the workflow is not yet registered.
func TestDaemonUpdate(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()

	var cpAddr string
	select {
	case cpAddr = <-started:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}
	ctl := protocol.NewClient(cpAddr)

	// Update before submit must fail.
	if _, err := ctl.Update(ctx, []byte(wfManualYAML)); err == nil {
		t.Fatal("update before submit should fail")
	}

	// Submit then update succeeds.
	if _, err := ctl.Submit(ctx, []byte(wfManualYAML)); err != nil {
		t.Fatalf("submit: %v", err)
	}
	if _, err := ctl.Update(ctx, []byte(wfManualYAML)); err != nil {
		t.Fatalf("update: %v", err)
	}

	cancel()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

const wfCronYAML = `
name: cron-demo
triggers:
  - type: cron
    schedule: "*/5 * * * *"
nodes:
  - type: shell
    name: tick
    command: "printf '{\"ok\":true}'"
`

// TestDaemonCronRegistration verifies that submitting a workflow with a cron
// trigger registers a scheduled task, and that disabling it unregisters it.
func TestDaemonCronRegistration(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()
	var cpAddr string
	select {
	case cpAddr = <-started:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}
	ctl := protocol.NewClient(cpAddr)

	// Submit then enable the cron workflow.
	if _, err := ctl.Submit(ctx, []byte(wfCronYAML)); err != nil {
		t.Fatalf("submit: %v", err)
	}
	if err := ctl.Enable(ctx, "cron-demo"); err != nil {
		t.Fatalf("enable: %v", err)
	}

	// Read the store from a second handle and confirm a scheduled task exists.
	store, err := honker.Open(dbPath, ext)
	if err != nil {
		t.Fatalf("open test store: %v", err)
	}
	soonest, err := store.Scheduler().Soonest()
	if err != nil || soonest <= 0 {
		t.Fatalf("expected a scheduled cron task after enable, got soonest=%d err=%v", soonest, err)
	}

	// Disable unregisters the task.
	if err := ctl.Disable(ctx, "cron-demo"); err != nil {
		t.Fatalf("disable: %v", err)
	}
	soonest, err = store.Scheduler().Soonest()
	if err != nil {
		t.Fatalf("soonest after disable: %v", err)
	}
	if soonest > 0 {
		t.Fatalf("expected no scheduled task after disable, got soonest=%d", soonest)
	}

	_ = store.Close()
	cancel()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

const wfEmailYAML = `
name: mail-demo
triggers:
  - type: email_received
    host: imap.gmail.com
    username: me@company.com
    secret: GMAIL_APP_PASSWORD
    poll: "*/5 * * * *"
nodes:
  - type: shell
    name: a
    command: "printf '{\"ok\":true}'"
`

// TestDaemonEmailRegistration verifies that submitting and enabling an
// `email_received` workflow registers a recurring poll on the scheduler, and
// that disabling unregisters it.
func TestDaemonEmailRegistration(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "d.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			Workers:      1,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()
	var cpAddr string
	select {
	case cpAddr = <-started:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not start")
	}
	ctl := protocol.NewClient(cpAddr)

	if _, err := ctl.Submit(ctx, []byte(wfEmailYAML)); err != nil {
		t.Fatalf("submit: %v", err)
	}
	if err := ctl.Enable(ctx, "mail-demo"); err != nil {
		t.Fatalf("enable: %v", err)
	}

	store, err := honker.Open(dbPath, ext)
	if err != nil {
		t.Fatalf("open test store: %v", err)
	}
	soonest, err := store.Scheduler().Soonest()
	if err != nil || soonest <= 0 {
		t.Fatalf("expected a scheduled email poll after enable, got soonest=%d err=%v", soonest, err)
	}

	if err := ctl.Disable(ctx, "mail-demo"); err != nil {
		t.Fatalf("disable: %v", err)
	}
	soonest, err = store.Scheduler().Soonest()
	if err != nil {
		t.Fatalf("soonest after disable: %v", err)
	}
	if soonest > 0 {
		t.Fatalf("expected no scheduled poll after disable, got soonest=%d", soonest)
	}

	_ = store.Close()
	cancel()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("daemon did not shut down")
	}
}

// TestDaemonWaitAndResume exercises the suspended-waits path end to end
// (ADR-0040, ADR-0042): boot a daemon with a worker, submit a workflow with a
// `wait` node, trigger it so it parks, then resume it by named signal and
// verify the run completes.
func TestDaemonWaitAndResume(t *testing.T) {
	ext := daemonExtPath(t)
	dbPath := filepath.Join(t.TempDir(), "wait.db")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	started := make(chan string, 1)
	done := make(chan error, 1)
	go func() {
		done <- Run(ctx, Config{
			Addr:         "127.0.0.1:0",
			DBPath:       dbPath,
			ExtPath:      ext,
			Workers:      1,
			DrainTimeout: 2 * time.Second,
			Started:      func(a string) { started <- a },
		})
	}()
	addr := <-started

	c := protocol.NewClient(addr)
	waitForHealth(t, c)

	wafer := `name: wf
triggers:
  - type: manual
nodes:
  - name: w
    type: wait
    signal: '"gate"'
  - name: b
    type: shell
    depends_on: [w]
    command: "printf '{\"ok\":true}'"
`
	if msg, err := c.Submit(ctx, []byte(wafer)); err != nil {
		t.Fatalf("submit: %v (%s)", err, msg)
	}
	if err := c.Enable(ctx, "wf"); err != nil {
		t.Fatalf("enable: %v", err)
	}
	if err := c.Trigger(ctx, "wf", []byte(`{}`)); err != nil {
		t.Fatalf("trigger: %v", err)
	}

	// Wait for the run to park (status waiting).
	waitForRunStatus(t, c, "running", honker.RunWaiting)

	// Resume by signal; the run should complete.
	if err := c.Resume(ctx, "gate", []byte(`{"approved":true}`)); err != nil {
		t.Fatalf("resume: %v", err)
	}
	waitForRunStatus(t, c, "waiting", honker.RunCompleted)

	cancel()
	<-done
}

// waitForHealth polls the daemon health endpoint until it answers.
func waitForHealth(t *testing.T, c *protocol.Client) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	for {
		if err := c.Health(ctx); err == nil {
			return
		}
		select {
		case <-ctx.Done():
			t.Fatalf("daemon never became healthy")
		case <-time.After(50 * time.Millisecond):
		}
	}
}

// waitForRunStatus polls runs until one run transitions from the given old
// status to want. It returns when a run reaches want.
func waitForRunStatus(t *testing.T, c *protocol.Client, old, want string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	for {
		body, err := c.ListRuns(ctx)
		if err == nil {
			var runs []struct {
				ID     string `json:"ID"`
				Status string `json:"Status"`
			}
			if json.Unmarshal([]byte(body), &runs) == nil {
				for _, r := range runs {
					if r.Status == want {
						return
					}
				}
			}
		}
		select {
		case <-ctx.Done():
			t.Fatalf("timed out waiting for run to become %s (was %s)", want, old)
		case <-time.After(50 * time.Millisecond):
		}
	}
}
